name: Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - '*'

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - uses: gradle/wrapper-validation-action@v1.0.4

      - name: Ktlint Check
        run: ./gradlew ktlintCheck

  jvm:
    runs-on: ubuntu-latest
    needs: ktlint

    strategy:
      matrix:
        java-version:
          - 11

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - uses: gradle/wrapper-validation-action@v1.0.4

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}

      - name: Test
        run: ./gradlew jvmTest

  node-js:
    runs-on: ubuntu-latest
    needs: ktlint

    strategy:
      matrix:
        node-version:
          - 14

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - uses: gradle/wrapper-validation-action@v1.0.4

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Test
        run: ./gradlew jsNodeTest

  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - jvm
      - node-js

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - uses: gradle/wrapper-validation-action@v1.0.4

      - uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Publish Snapshot
        run: ./gradlew uploadArchives --no-daemon --no-parallel
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
