name: Validate Gradle Wrapper
on: [push]

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate
        uses: gradle/wrapper-validation-action@v1
